# Generated by Django 3.1.7 on 2021-05-03 17:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='teachers',
        ),
        migrations.AddField(
            model_name='group',
            name='teachers',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.teacher'),
        ),
    ]
