# Generated by Django 3.1.7 on 2021-05-03 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210503_1717'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group',
            old_name='teachers',
            new_name='teacher',
        ),
    ]
