# Generated by Django 3.1.7 on 2021-05-03 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20210503_1738'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group',
            old_name='teacher',
            new_name='teachers',
        ),
    ]
