# Generated by Django 3.1.7 on 2021-05-10 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20210504_0753'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonoBankParseData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(max_length=255)),
                ('rate', models.FloatField()),
            ],
        ),
    ]
